/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 29 06:34:57 GMT 2018
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class LC_4_ESTest extends LC_4_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      int[] intArray0 = new int[4];
      int[] intArray1 = new int[7];
      LC_4.findMedianSortedArrays(intArray0, intArray1);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      int[] intArray0 = new int[3];
      intArray0[1] = 1;
      LC_4.findMedianSortedArrays((int[]) null, intArray0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      int[] intArray0 = new int[11];
      LC_4.findMedianSortedArrays((int[]) null, intArray0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      LC_4.doubleToString("");
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      // Undeclared exception!
      try { 
        LC_4.stringToIntegerArray(",");

      
      } catch(StringIndexOutOfBoundsException e) {
          fail("Expecting exception: StringIndexOutOfBoundsException");
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      // Undeclared exception!
      try { 
        LC_4.stringToIntegerArray((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
          fail("Expecting exception: NullPointerException");
         verifyException("LC_4", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      String[] stringArray0 = new String[7];
      // Undeclared exception!
      try { 
        LC_4.doubleToString(stringArray0[2]);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("LC_4", e);
          fail("Expecting exception: NullPointerException");
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      // Undeclared exception!
      try { 
        LC_4.ALLToString("");
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
          fail("Expecting exception: StringIndexOutOfBoundsException");
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      // Undeclared exception!
      try { 
        LC_4.ALLToString((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("LC_4", e);
          fail("Expecting exception: NullPointerException");
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      LC_4.ALLToString("!l_{p");
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      // Undeclared exception!
      LC_4.doubleToString("Kae.dG V7T!chdb");
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      LC_4.doubleToString("`'");
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      int[] intArray0 = new int[6];
      intArray0[3] = (-1431655765);
      intArray0[5] = (-76);
      int[] intArray1 = new int[6];
      LC_4.findMedianSortedArrays(intArray0, intArray1);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      int[] intArray0 = new int[4];
      intArray0[2] = (-428);
      intArray0[3] = (-1585);
      LC_4.findMedianSortedArrays(intArray0, intArray0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      // Undeclared exception!
      try { 
        LC_4.findMedianSortedArrays((int[]) null, (int[]) null);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("LC_4", e);
          fail("Expecting exception: ArrayIndexOutOfBoundsException");
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      int[] intArray0 = LC_4.stringToIntegerArray("`1W");
      assertArrayEquals(new int[] {1}, intArray0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      int[] intArray0 = LC_4.stringToIntegerArray("4V");
      assertEquals(0, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      // Undeclared exception!
      try { 
        LC_4.stringToIntegerArray("*3,BCj\"O.cY>*");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // For input string: \"BCj\"O.cY>\"
         //
         verifyException("java.lang.NumberFormatException", e);
          fail("Expecting exception: NumberFormatException");
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      String[] stringArray0 = new String[3];
      LC_4.main(stringArray0);
      assertEquals(3, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      LC_4 lC_4_0 = new LC_4();
  }
}
