/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 29 06:54:34 GMT 2018
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class LC_3_ESTest extends LC_3_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      int[] intArray0 = new int[0];
      // Undeclared exception!
      try { 
        LC_3.findMedianSortedArrays(intArray0, intArray0, ">'Q6?|,x2Ci67]BYkf");
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("LC_3", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LC_3 lC_3_0 = new LC_3();
      int[] intArray0 = null;
      // Undeclared exception!
      try { 
        LC_3.findMedianSortedArrays((int[]) null, (int[]) null, "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("LC_3", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int[] intArray0 = new int[0];
      int[] intArray1 = new int[5];
      int int0 = 3144;
      intArray1[0] = 3144;
      int int1 = (-344);
      intArray1[1] = (-344);
      int int2 = 0;
      intArray1[2] = 0;
      int int3 = 584;
      intArray1[3] = 584;
      int int4 = 3948;
      intArray1[4] = 3948;
      String string0 = "";
      // Undeclared exception!
      LC_3.findMedianSortedArrays(intArray0, intArray1, "");
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LC_3 lC_3_0 = new LC_3();
      int[] intArray0 = new int[6];
      int int0 = 1657;
      intArray0[0] = 1657;
      int int1 = 4573;
      intArray0[1] = 4573;
      int int2 = 1362;
      intArray0[2] = 1362;
      intArray0[3] = (-2299);
      int int3 = 0;
      intArray0[4] = 0;
      intArray0[5] = 0;
      String string0 = null;
      // Undeclared exception!
      LC_3.findMedianSortedArrays(intArray0, intArray0, (String) null);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      LC_3 lC_3_0 = new LC_3();
      int[] intArray0 = new int[8];
      intArray0[0] = (-1);
      intArray0[1] = 0;
      intArray0[2] = 0;
      intArray0[3] = 0;
      intArray0[4] = 0;
      intArray0[5] = (-1598);
      intArray0[6] = 456;
      intArray0[7] = 0;
      int[] intArray1 = new int[2];
      intArray1[0] = 456;
      intArray1[1] = 0;
      // Undeclared exception!
      LC_3.findMedianSortedArrays(intArray0, intArray1, "");
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      int[] intArray0 = new int[0];
      String string0 = null;
      // Undeclared exception!
      try { 
        LC_3.findMedianSortedArrays(intArray0, intArray0, (String) null);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("LC_3", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      int[] intArray0 = null;
      // Undeclared exception!
      try { 
        LC_3.findMedianSortedArrays((int[]) null, (int[]) null, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("LC_3", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      int[] intArray0 = new int[0];
      String string0 = "2Wqh'C-y3-";
      // Undeclared exception!
      try { 
        LC_3.findMedianSortedArrays(intArray0, intArray0, "2Wqh'C-y3-");
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("LC_3", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      int[] intArray0 = new int[5];
      intArray0[0] = (-1306);
      intArray0[1] = (-111);
      intArray0[2] = 2736;
      intArray0[3] = (-772);
      intArray0[4] = (-4374);
      // Undeclared exception!
      LC_3.findMedianSortedArrays(intArray0, intArray0, "*[p+<yvb");
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      int[] intArray0 = new int[2];
      intArray0[0] = 0;
      intArray0[1] = 0;
      // Undeclared exception!
      LC_3.findMedianSortedArrays(intArray0, intArray0, "|c>xnL<R? W,9");
  }
}
